### ISSUE TITLE
Nurbs Curve Conversion issue

### ISSUE THREAD

**Issue by cerver** [mcneel/rhino.inside#221]
When converting from nurbs curve the function in Convert.cs at line 1139 incorrectly identifies parts of the nurbs curve as an ellipse . commenting out produces  a valid result. 

specific error : 
Autodesk.Revit.Exceptions.ArgumentOutOfRangeException
  HResult=0x80131500
  Message=The given value for xRadius must be greater than 0 and no more than 30000 feet.
Parameter name: xRadius
  Source=RevitAPI
  StackTrace:
   at Autodesk.Revit.CurveAPIUtils.CreateEllipse(XYZ center, Double xRadius, Double yRadius, XYZ xAxis, XYZ yAxis, Double startParameter, Double endParameter, Boolean allowSimplification)
   at Autodesk.Revit.DB.Ellipse.CreateCurve(XYZ center, Double xRadius, Double yRadius, XYZ xAxis, XYZ yAxis, Double startParameter, Double endParameter)
   at RhinoInside.Revit.Convert.ToHost(Ellipse ellipse, Interval interval) in D:\Dropbox\CDS_Code\rhino.inside\Autodesk\Revit\src\RhinoInside.Revit\Convert.cs:line 920
   at RhinoInside.Revit.Convert.<ToHostMultiple>d__56.MoveNext() in D:\Dropbox\CDS_Code\rhino.inside\Autodesk\Revit\src\RhinoInside.Revit\Convert.cs:line 1141
   at RhinoInside.Revit.Convert.<ToHostMultiple>d__56.MoveNext() in D:\Dropbox\CDS_Code\rhino.inside\Autodesk\Revit\src\RhinoInside.Revit\Convert.cs:line 1119
   at RhinoInside.Revit.Convert.ToCurveArray(IEnumerable`1 curves) in D:\Dropbox\CDS_Code\rhino.inside\Autodesk\Revit\src\RhinoInside.Revit\Convert.cs:line 1589
   at RhinoInside.Revit.GH.Components.FloorByOutline.ReconstructFloorByOutline(Document doc, Element& element, Curve boundary, Optional`1 type, Optional`1 level, Boolean structural) in D:\Dropbox\CDS_Code\rhino.inside\Autodesk\Revit\src\RhinoInside.Revit\GH\Element\Floor\ByOutline.cs:line 53

**Comment by kike-garbo** [comment]
Hi,

Can you share a Revit document that contains that NURBS?
